### ISSUE TITLE
ember-precompile - SyntaxError: Unexpected token ) 

### ISSUE THREAD

**Issue by Soullivaneuh** [ucsf-ckm/symfony-emberjs-edition#8]
Hi,

Just installed you project, I have the following error on `assetic:dump` command:

```
                                                                                                                                                  
  [Assetic\Exception\FilterException]                                                                                                               
  An error occurred while running:                                                                                                                  
  '/usr/local/bin/node' '/usr/local/bin/ember-precompile' '/tmp/assetic_ember_in5506f5475eafe/application.hbs' '-f' '/tmp/assetic_ember_outoJOn3e'  
  Error Output:                                                                                                                                     
  /usr/local/lib/node_modules/ember-precompile/node_modules/jquery/node_modules/jsdom/lib/jsdom/level1/core.js:418                                  
    set nodeName() { throw new core.DOMException();},                                                                                               
                 ^                                                                                                                                  
  SyntaxError: Unexpected token )                                                                                                                   
      at exports.runInThisContext (vm.js:73:16)                                                                                                     
      at Module._compile (module.js:443:25)                                                                                                         
      at Object.Module._extensions..js (module.js:478:10)                                                                                           
      at Module.load (module.js:355:32)                                                                                                             
      at Function.Module._load (module.js:310:12)                                                                                                   
      at Module.require (module.js:365:17)                                                                                                          
      at require (module.js:384:17)                                                                                                                 
      at Object.<anonymous> (/usr/local/lib/node_modules/ember-precompile/node_modules/jquery/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)     
      at Module._compile (module.js:460:26)                                                                                                         
      at Object.Module._extensions..js (module.js:478:10)                                                                                           
  Input:                                                                                                                                            
  <nav>                                                                                                                                             
    {{#link-to "index"}}Home{{/link-to}}                                                                                                            
    {{#link-to "categories"}}Categories{{/link-to}}                                                                                                 
    {{#link-to "products"}}Products{{/link-to}}                                                                                                     
  </nav>                                                                                                                                            
  {{outlet}}
```

Any idea?

Thanks.

**Comment by hacfi** [comment]
@Soullivaneuh Are you running node 0.12.X? Can you try with node 0.10.X? I run to these kind of issues a lot lately (back to 0.10.X for now).

**Comment by jrjohnson** [comment]
@Soullivaneuh  - if you haven't already try using [nvm](https://github.com/creationix/nvm) to manage the node version on your machine.  It makes switch back and forth easy.

**Comment by Soullivaneuh** [comment]
Indeed, works with node 0.10.x.

Is 0.12.x still an unstable version of node?

Thanks.

**Comment by jrjohnson** [comment]
I haven't dug into why 0.12 isn't working yet its supposed to be stable, but I'm guessing it was in development for so long that many people stopped thinking bout it.  So various libraries have issues that will get sorted out over the next few months.
